// Copies the canonical data + assets from the repo root into web/public so the
// React app stays in sync with the legacy site's single source of truth.
// Runs automatically before `dev` and `build`.
import { cpSync, mkdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..', '..');
const pub = resolve(here, '..', 'public');

const files = [
  ['workflows.json', 'workflows.json'],
  ['openapi.json', 'openapi.json'],
  ['skills/skills.json', 'skills.json'],
];
const dirs = [['assets', 'assets']];

mkdirSync(pub, { recursive: true });
for (const [src, dst] of files) {
  const from = resolve(repo, src);
  if (existsSync(from)) cpSync(from, resolve(pub, dst));
  else console.warn('sync-data: missing', src);
}
for (const [src, dst] of dirs) {
  const from = resolve(repo, src);
  if (existsSync(from)) cpSync(from, resolve(pub, dst), { recursive: true });
}
console.log('sync-data: copied data + assets into web/public');

// Emit a compact catalogue index for the Vercel serverless functions (web/api/).
function compact(items, pick) {
  return items.map((it) => ({
    id: it.id,
    name: it.name,
    category: it.category || '',
    description: (it.description || '').slice(0, 280),
    status: pick(it) || '',
  }));
}

const apiDir = resolve(here, '..', 'api');
mkdirSync(apiDir, { recursive: true });

const workflows = JSON.parse(readFileSync(resolve(repo, 'workflows.json'), 'utf8')).workflows || [];
const skills = JSON.parse(readFileSync(resolve(repo, 'skills/skills.json'), 'utf8')).skills || [];

const index = {
  workflows: compact(workflows, (w) => {
    const validated = Object.entries(w.platform_status || {})
      .filter(([, v]) => v && v !== 'guide-only')
      .map(([k]) => k);
    return validated.length ? `${validated.length} platforms` : '';
  }),
  skills: compact(skills, (s) => s.status || ''),
};

writeFileSync(
  resolve(apiDir, '_catalog-index.js'),
  '// Generated by scripts/sync-data.mjs — do not edit by hand.\n' +
    `export const catalog = ${JSON.stringify(index, null, 2)};\n`,
);
console.log('sync-data: wrote web/api/_catalog-index.js');
