// Copies the canonical data + assets from the repo root into web/public so the
// React app stays in sync with the legacy site's single source of truth.
// Runs automatically before `dev` and `build`.
import { cpSync, mkdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MCP_TOOLS } from '../src/data/mcpTools.js';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..', '..');
const pub = resolve(here, '..', 'public');

const files = [
  ['workflows.json', 'workflows.json'],
  ['openapi.json', 'openapi.json'],
  ['skills/skills.json', 'skills.json'],
];
const dirs = [['assets', 'assets']];

mkdirSync(pub, { recursive: true });
for (const [src, dst] of files) {
  const from = resolve(repo, src);
  if (existsSync(from)) cpSync(from, resolve(pub, dst));
  else console.warn('sync-data: missing', src);
}
for (const [src, dst] of dirs) {
  const from = resolve(repo, src);
  if (existsSync(from)) cpSync(from, resolve(pub, dst), { recursive: true });
}
console.log('sync-data: copied data + assets into web/public');

// Emit a compact catalogue index for the Vercel serverless functions (web/api/).
function compact(items, pick) {
  return items.map((it) => ({
    id: it.id,
    name: it.name,
    category: it.category || '',
    description: (it.description || '').slice(0, 280),
    status: pick(it) || '',
  }));
}

const apiDir = resolve(here, '..', 'api');
mkdirSync(apiDir, { recursive: true });

const workflows = JSON.parse(readFileSync(resolve(repo, 'workflows.json'), 'utf8')).workflows || [];
const skills = JSON.parse(readFileSync(resolve(repo, 'skills/skills.json'), 'utf8')).skills || [];

// Map each MCP tool to the signals (skills) that use it, so the assistant can
// explain what each Backstory MCP tool does and which signals rely on it.
const toolUsage = {};
for (const s of skills) {
  for (const t of s.mcpTools || []) (toolUsage[t] = toolUsage[t] || []).push(s.name);
}
const mcp = MCP_TOOLS.map((t) => ({
  name: t.name,
  description: t.description,
  usedBy: toolUsage[t.name] || [],
}));

const index = {
  workflows: compact(workflows, (w) => {
    const validated = Object.entries(w.platform_status || {})
      .filter(([, v]) => v && v !== 'guide-only')
      .map(([k]) => k);
    return validated.length ? `${validated.length} platforms` : '';
  }),
  skills: compact(skills, (s) => s.status || ''),
  mcp,
};

writeFileSync(
  resolve(apiDir, '_catalog-index.js'),
  '// Generated by scripts/sync-data.mjs — do not edit by hand.\n' +
    `export const catalog = ${JSON.stringify(index, null, 2)};\n`,
);
console.log('sync-data: wrote web/api/_catalog-index.js');

// Copy each workflow's downloadable platform assets into web/public/downloads/<id>/<file>
// so the detail page can serve them (base-path aware via assetUrl).
const dlRoot = resolve(pub, 'downloads');
mkdirSync(dlRoot, { recursive: true });
let copied = 0;
for (const wf of workflows) {
  const files = new Set(Object.values(wf.platforms || {}).filter(Boolean));
  for (const f of files) {
    const from = resolve(repo, wf.id, f);
    if (existsSync(from)) {
      const destDir = resolve(dlRoot, wf.id);
      mkdirSync(destDir, { recursive: true });
      cpSync(from, resolve(destDir, f));
      copied++;
    }
  }
}
console.log(`sync-data: copied ${copied} workflow download assets into web/public/downloads`);

// Serve the legacy single-file site at /legacy/ for pages not yet ported to React
// (Opp Insights, Setup Guides). The legacy index.html uses relative paths, so we
// co-locate its data + assets under web/public/legacy/.
const legacyDir = resolve(pub, 'legacy');
mkdirSync(legacyDir, { recursive: true });
const legacyFiles = [
  ['index.html', 'index.html'],
  ['workflows.json', 'workflows.json'],
  ['openapi.json', 'openapi.json'],
  ['skills/skills.json', 'skills/skills.json'],
];
for (const [src, dst] of legacyFiles) {
  const from = resolve(repo, src);
  if (existsSync(from)) {
    const to = resolve(legacyDir, dst);
    mkdirSync(dirname(to), { recursive: true });
    cpSync(from, to);
  }
}
const legacyAssets = resolve(repo, 'assets');
if (existsSync(legacyAssets)) cpSync(legacyAssets, resolve(legacyDir, 'assets'), { recursive: true });
console.log('sync-data: copied legacy site into web/public/legacy');
