// Generated by scripts/sync-data.mjs — do not edit by hand.
export const catalog = {
  "workflows": [
    {
      "id": "01-sales-digest",
      "name": "Sales Digest",
      "category": "daily-intelligence",
      "description": "Generates a personalized daily sales digest for each enrolled user. At 6 AM on weekdays, the workflow retrieves the list of digest subscribers from the User Config Store, queries Backstory via MCP for each user's relevant account and opportunity activity, then passes the data to ",
      "status": ""
    },
    {
      "id": "02-meeting-brief",
      "name": "Meeting Brief",
      "category": "daily-intelligence",
      "description": "Prepares an AI-generated briefing document before each upcoming meeting. A parent cron workflow fires every 15 minutes and invokes this sub-workflow for meetings approaching on the calendar. The workflow fetches account context from Backstory via MCP — recent activity, engagement",
      "status": ""
    },
    {
      "id": "03-silence-contract-monitor",
      "name": "Silence & Contract Monitor",
      "category": "account-monitoring",
      "description": "Monitors accounts for engagement gaps that may signal churn risk. Every morning at 6:30 AM, the workflow pulls accounts and checks for those that have \"gone silent\" — no meaningful engagement activity within a configured lookback window. For flagged accounts, it uses the LLM to a",
      "status": ""
    },
    {
      "id": "04-opportunity-discovery",
      "name": "Opportunity Discovery",
      "category": "pipeline-forecasting",
      "description": "Surfaces hidden revenue opportunities by identifying accounts with recent engagement activity but no corresponding open opportunities in the pipeline. On a weekly cadence, the workflow cross-references Backstory activity data against the CRM pipeline, flags accounts showing buyin",
      "status": ""
    },
    {
      "id": "05-forecast-coach",
      "name": "Forecast Coach",
      "category": "pipeline-forecasting",
      "description": "Provides AI-powered coaching insights for sales leaders by analyzing their team's open pipeline each week. Every Monday, the workflow pulls each leader's team pipeline from Backstory, filters for active deals, and uses the LLM to assess deal health — looking at engagement recency",
      "status": ""
    },
    {
      "id": "06-executive-inbox",
      "name": "Executive Inbox",
      "category": "account-monitoring",
      "description": "Automates executive email triage by reading unread email messages, identifying those from customers or prospects, enriching them with CRM context from Backstory, and using AI to classify and route each message. The AI Agent analyzes the email content alongside account history to ",
      "status": ""
    },
    {
      "id": "07-churn-risk-scorecard",
      "name": "Churn Risk Scorecard",
      "category": "customer-success",
      "description": "Generates a weekly churn risk scorecard for the customer success team. The workflow pulls engagement trends, support ticket volumes, champion contact activity, and product usage signals from Backstory and the CRM. An AI agent scores each account on a 1-10 churn risk scale, identi",
      "status": ""
    },
    {
      "id": "08-renewal-prep-brief",
      "name": "Renewal Prep Brief",
      "category": "customer-success",
      "description": "Automatically generates renewal preparation briefs at 60, 30, and 15 days before each account's renewal date. The workflow queries the CRM for upcoming renewals, enriches each account with Backstory engagement trends, support history, expansion signals, and key contact activity. ",
      "status": ""
    },
    {
      "id": "09-onboarding-pulse",
      "name": "Onboarding Pulse",
      "category": "customer-success",
      "description": "Monitors newly closed deals during their first 90 days to detect accounts going dark before they become a retention problem. The workflow identifies recently closed-won accounts, checks Backstory engagement data for post-sale activity (meetings booked, emails exchanged, contacts ",
      "status": ""
    },
    {
      "id": "10-activity-gap-detector",
      "name": "Activity Gap Detector",
      "category": "coaching-enablement",
      "description": "Compares each rep's weekly activity patterns against team benchmarks and top performer profiles using Backstory activity data. Identifies reps with low outbound activity, thin multi-threading on key deals, or single-threaded opportunities missing executive engagement. An AI agent",
      "status": ""
    },
    {
      "id": "11-deal-hygiene-audit",
      "name": "Deal Hygiene Audit",
      "category": "coaching-enablement",
      "description": "Performs a weekly pipeline hygiene audit by scanning all open opportunities in the CRM and cross-referencing with Backstory engagement data. Flags deals with stale close dates, no recent activity, missing next steps, single-threaded contacts, or no executive engagement. An AI age",
      "status": ""
    },
    {
      "id": "12-win-loss-debrief",
      "name": "Win/Loss Debrief Generator",
      "category": "coaching-enablement",
      "description": "Automatically generates a structured win/loss debrief when any deal closes (won or lost). Triggered by a CRM webhook on stage change, the workflow pulls the full engagement timeline from Backstory — every meeting, email, contact involved, and engagement cadence throughout the dea",
      "status": ""
    },
    {
      "id": "13-competitive-displacement-alert",
      "name": "Competitive Displacement Alert",
      "category": "strategic-intelligence",
      "description": "Monitors customer accounts for early signs of competitive displacement. The workflow scans Backstory engagement data for accounts where internal engagement has suddenly dropped while simultaneously checking for competitor mentions in email subjects, meeting titles, or CRM notes. ",
      "status": ""
    },
    {
      "id": "14-territory-heat-map",
      "name": "Territory Heat Map",
      "category": "strategic-intelligence",
      "description": "Generates a weekly territory heat map digest for each rep, showing which accounts in their territory are heating up (increased inbound, new contacts engaging, meeting frequency rising) versus cooling down (declining engagement, unresponsive contacts). The workflow pulls Backstory",
      "status": ""
    },
    {
      "id": "15-qbr-auto-prep",
      "name": "QBR Auto-Prep",
      "category": "strategic-intelligence",
      "description": "Automatically prepares quarterly business review materials for every account on an upcoming QBR agenda. The workflow scans the calendar for meetings tagged as QBRs (or matching configurable title patterns), then for each account on the agenda, pulls the full quarter's engagement ",
      "status": ""
    },
    {
      "id": "16-executive-sponsor-tracker",
      "name": "Executive Sponsor Tracker",
      "category": "strategic-intelligence",
      "description": "Monitors executive-level contact engagement across strategic deals to ensure champion and sponsor relationships stay active. The workflow identifies open opportunities above a configurable deal value threshold, checks Backstory for executive contact engagement (VP+ titles), and f",
      "status": ""
    },
    {
      "id": "17-marketing-sales-handoff-scorer",
      "name": "Marketing-to-Sales Handoff Scorer",
      "category": "pipeline-forecasting",
      "description": "Enriches marketing-qualified leads at the moment of handoff by checking Backstory for existing engagement history. When a new MQL is created in the CRM or marketing automation platform, the workflow queries Backstory to see if the account already has relationship history — prior ",
      "status": ""
    },
    {
      "id": "18-channel-pulse",
      "name": "Channel Pulse",
      "category": "account-monitoring",
      "description": "Sends quick, 60-second scannable updates to internal customer channels with relevant account information from the last 7 days. Designed to keep the extended team and executives abreast of what's happening in key accounts without requiring them to dig through CRM data or attend ev",
      "status": ""
    },
    {
      "id": "19-customer-stack-blueprint",
      "name": "Customer Stack Blueprint",
      "category": "platform-enablement",
      "description": "Turns a customer workflow request and tool-stack intake into a reusable implementation blueprint that recommends the closest validated asset, the right orchestration recipe, and the connector substitutions required for CRM, delivery, and meeting-source differences.",
      "status": ""
    },
    {
      "id": "20-crm-signal-normalizer",
      "name": "CRM Signal Normalizer",
      "category": "platform-enablement",
      "description": "Normalizes Salesforce, Dynamics 365, HubSpot, or custom CRM records into a canonical account, contact, opportunity, and activity payload so downstream Backstory workflows can be reused without forking business logic by CRM.",
      "status": ""
    },
    {
      "id": "21-meeting-intelligence-normalizer",
      "name": "Meeting Intelligence Normalizer",
      "category": "platform-enablement",
      "description": "Normalizes meetings, transcripts, attendees, and action items from Gong, Zoom, Teams, Otter, Fireflies, Fathom, and other note-taker systems into one reusable meeting-intelligence payload for prep, coaching, and QBR workflows.",
      "status": ""
    },
    {
      "id": "22-multi-channel-delivery-router",
      "name": "Multi-Channel Delivery Router",
      "category": "platform-enablement",
      "description": "Receives a ready-to-send insight payload, resolves whether it should land in Slack, Teams, email, or a webhook, adapts the format for that surface, and applies fallback routing without cloning the business logic for each tool.",
      "status": ""
    },
    {
      "id": "23-identity-resolution-hub",
      "name": "Identity Resolution Hub",
      "category": "platform-enablement",
      "description": "Resolves people, account, owner, and channel identities across CRM, messaging, and meeting systems into a canonical identity layer so downstream workflows stop breaking on duplicate humans, alias drift, and ambiguous account ownership.",
      "status": ""
    },
    {
      "id": "24-workflow-contract-validator",
      "name": "Workflow Contract Validator",
      "category": "platform-enablement",
      "description": "Validates canonical payloads between workflow steps so schema drift, missing fields, enum changes, and connector-specific shape changes are caught before they break downstream automations.",
      "status": ""
    },
    {
      "id": "25-implementation-gap-audit",
      "name": "Implementation Gap Audit",
      "category": "platform-enablement",
      "description": "Audits a customer stack or internal workflow request against the current library to identify what is already validated, what only has recipe coverage, and what still needs productization work before rollout.",
      "status": ""
    },
    {
      "id": "26-orchestrator-migration-planner",
      "name": "Orchestrator Migration Planner",
      "category": "platform-enablement",
      "description": "Transforms a validated workflow pattern plus source-tool implementation details into a migration plan for n8n, Make, Power Automate, Zapier, Workato, or custom code without losing workflow order, state handling, payload contracts, or delivery behavior.",
      "status": ""
    },
    {
      "id": "27-adapter-regression-monitor",
      "name": "Adapter Regression Monitor",
      "category": "platform-enablement",
      "description": "Replays golden payloads through CRM, meeting, identity, and delivery adapters to catch functional regressions before connector changes break reusable workflow patterns.",
      "status": ""
    },
    {
      "id": "28-rollout-readiness-scorecard",
      "name": "Rollout Readiness Scorecard",
      "category": "platform-enablement",
      "description": "Scores whether a customer stack is actually ready for deployment by evaluating connector access, identity coverage, delivery routes, ownership, security prerequisites, and QA gates before a workflow goes live.",
      "status": ""
    },
    {
      "id": "29-digital-chief-of-staff",
      "name": "Digital Chief of Staff",
      "category": "strategic-intelligence",
      "description": "Reference-grade Digital Chief of Staff workflow that combines account-channel updates, executive briefing synthesis, and calendar task generation using shared n8n sub-workflows plus bounded MCP enrichment.",
      "status": ""
    },
    {
      "id": "30-market-research-brief",
      "name": "Market Research Brief",
      "category": "strategic-intelligence",
      "description": "Builds a weekly market-intelligence digest for target accounts by combining normalized external company-signal packets with Backstory relationship and opportunity context.",
      "status": ""
    },
    {
      "id": "31-deal-inspection",
      "name": "Deal Inspection (Slack /dealcheck)",
      "category": "pipeline-forecasting",
      "description": "Runs a slash-command deal inspection by resolving the requested account and opportunity, pulling Backstory deal context, and returning the top risk, supporting evidence, and next actions in Slack.",
      "status": ""
    },
    {
      "id": "32-revenue-orchestration",
      "name": "Revenue Orchestration (Approval-Gated)",
      "category": "pipeline-forecasting",
      "description": "Takes an external revenue signal, builds a proposed CRM update plus owner message, and pauses for Slack approval before sending the approved action downstream.",
      "status": ""
    },
    {
      "id": "33-prospecting-brief",
      "name": "Prospecting Brief",
      "category": "strategic-intelligence",
      "description": "Builds an on-demand prospecting brief by combining account status, recent account activity, and situation context into tailored outreach angles and next steps.",
      "status": ""
    },
    {
      "id": "34-manager-coaching-brief",
      "name": "Manager Coaching Brief",
      "category": "coaching-enablement",
      "description": "Creates an on-demand manager coaching brief by combining opportunity status, scorecard signal, and situation context into coaching points for the rep and manager.",
      "status": ""
    },
    {
      "id": "35-grounded-follow-up",
      "name": "Content Generation — Grounded Follow-Up",
      "category": "coaching-enablement",
      "description": "Generates a grounded follow-up draft using recent opportunity activity, deal-risk context, and situation evidence so the outbound message stays tied to the actual deal state.",
      "status": ""
    },
    {
      "id": "36-pipeline-forecast-digest",
      "name": "Pipeline & Forecast Digest",
      "category": "pipeline-forecasting",
      "description": "Builds a pipeline and forecast digest by pulling top records, expanding at-risk opportunities, enriching each one with context, and summarizing the highest-priority forecast issues in Slack.",
      "status": ""
    },
    {
      "id": "37-deal-risk-next-actions",
      "name": "AI Agents — Deal Risk + Next Actions",
      "category": "pipeline-forecasting",
      "description": "Creates an on-demand deal-risk brief by merging opportunity status, recent activity, engaged-person context, and situation evidence into a concise risk and next-action recommendation.",
      "status": ""
    },
    {
      "id": "38-account-planning-strategy",
      "name": "Account Planning & Strategy",
      "category": "strategic-intelligence",
      "description": "Generates an account-planning strategy brief by combining account status, recent account activity, stakeholder engagement, and situation context into account-level priorities and next steps.",
      "status": ""
    }
  ],
  "skills": [
    {
      "id": "01-account-plan-agent",
      "name": "Account Plan Agent",
      "category": "account-research",
      "description": "Transforms static account plans into dynamic, interactive dashboards with real-time intelligence and actionable insights.",
      "status": ""
    },
    {
      "id": "02-external-company-news-agent",
      "name": "External Company News Agent",
      "category": "account-research",
      "description": "Gathers, analyzes, and synthesizes external market intelligence for target accounts — public company data, financial reports, earnings calls, and strategic insights.",
      "status": ""
    },
    {
      "id": "03-relationship-map-agent",
      "name": "Relationship Map Agent",
      "category": "account-research",
      "description": "Creates professional, interactive relationship influence maps showing stakeholder connections, power dynamics, and engagement levels.",
      "status": ""
    },
    {
      "id": "04-customer-sentiment-agent",
      "name": "Customer Sentiment Agent",
      "category": "account-research",
      "description": "Comprehensive framework for analyzing customer sentiment trends using Backstory MCP data sources. Identifies risk signals and positive momentum.",
      "status": ""
    },
    {
      "id": "05-opportunity-agent",
      "name": "Opportunity Agent",
      "category": "opportunity-management",
      "description": "Creates actionable opportunity health dashboards — deal health scoring, stakeholder engagement analysis, risk assessment, and strategic outreach recommendations.",
      "status": ""
    },
    {
      "id": "06-meddpicc-agent",
      "name": "MEDDPICC Agent",
      "category": "opportunity-management",
      "description": "AI-powered MEDDPICC qualification system that automatically assesses and improves qualification status from communication data.",
      "status": ""
    },
    {
      "id": "07-win-probability-agent",
      "name": "Win Probability Agent",
      "category": "opportunity-management",
      "description": "Real-time, time-sensitive win probability scoring for sales opportunities. Factors in timeline pressure — same qualification gaps have different impact based on time available.",
      "status": ""
    },
    {
      "id": "08-meeting-prep-agent",
      "name": "Meeting Prep Agent",
      "category": "meeting-review-prep",
      "description": "Generates a concise one-page briefing before any customer meeting — recent activity, open issues, stakeholder context, talking points, and risks to address.",
      "status": ""
    },
    {
      "id": "09-qbr-generator-agent",
      "name": "QBR Generator Agent",
      "category": "meeting-review-prep",
      "description": "Generates draft Quarterly Business Review content — value delivered, engagement trends, risks, renewal readiness, and recommended discussion topics.",
      "status": ""
    },
    {
      "id": "10-multi-threading-coach-agent",
      "name": "Multi-Threading Coach Agent",
      "category": "action-growth",
      "description": "Identifies single-threaded relationship risk across opportunities and recommends specific people to engage based on engagement data and org structure.",
      "status": ""
    },
    {
      "id": "11-next-best-action-agent",
      "name": "Next Best Action Agent",
      "category": "action-growth",
      "description": "Surfaces the top 3 actions to take today across your accounts — prioritized by urgency, deal value, and risk signals from recent activity.",
      "status": ""
    },
    {
      "id": "12-whitespace-mapper-agent",
      "name": "Whitespace Mapper Agent",
      "category": "action-growth",
      "description": "Identifies expansion opportunities by analyzing engaged stakeholders across departments and business units — surfaces where engagement exists but revenue doesn't.",
      "status": ""
    },
    {
      "id": "13-pipeline-review-agent",
      "name": "Pipeline Review Agent",
      "category": "action-growth",
      "description": "Portfolio-level pipeline review for managers — aggregates deal health, stalled opportunities, coaching priorities, and forecast risks across multiple accounts.",
      "status": ""
    },
    {
      "id": "14-competitive-battle-card-agent",
      "name": "Competitive Battle Card Agent",
      "category": "action-growth",
      "description": "Generates live competitive battle cards when competitors surface in deal activity — positioning, differentiators, talk tracks, and objection handling from deal context.",
      "status": ""
    },
    {
      "id": "15-executive-briefing-agent",
      "name": "Executive Briefing Agent",
      "category": "action-growth",
      "description": "Internal-facing executive summary for when leadership asks \"what's going on with this account?\" — pipeline risk, revenue impact, and strategic posture in one concise brief.",
      "status": ""
    },
    {
      "id": "16-renewal-risk-agent",
      "name": "Renewal Risk Agent",
      "category": "action-growth",
      "description": "Predicts renewal likelihood by scoring engagement decay, sentiment shifts, stakeholder turnover, and competitive mentions — then generates a save plan for at-risk accounts.",
      "status": ""
    },
    {
      "id": "17-handoff-agent",
      "name": "Handoff Agent",
      "category": "transitions-learning",
      "description": "Generates comprehensive account handoff documents when a rep or CSM transitions — relationship history, stakeholder map, open issues, deal context, and personality insights from communication tone.",
      "status": ""
    },
    {
      "id": "18-deal-debrief-agent",
      "name": "Deal Debrief Agent",
      "category": "transitions-learning",
      "description": "Post-close analysis for won or lost deals — what worked, what didn't, decisive stakeholders, competitive dynamics, and lessons learned for institutional knowledge.",
      "status": ""
    },
    {
      "id": "19-engagement-scorecard-agent",
      "name": "Engagement Scorecard Agent",
      "category": "engagement-analytics",
      "description": "Weekly/monthly engagement metrics report — trending up or down, who's going dark, who's newly active. Pure data-driven engagement tracking.",
      "status": ""
    },
    {
      "id": "20-opportunity-insights-agent",
      "name": "Opportunity Insights Agent",
      "category": "opportunity-management",
      "description": "Builds interactive pipeline intelligence dashboards that classify every open opportunity into Stalled, At Risk, Hidden Upside, or Acceleration insights — surfacing critical deal patterns days before they're obvious in CRM.",
      "status": ""
    },
    {
      "id": "21-workflow-template-architect",
      "name": "Workflow Template Architect",
      "category": "platform-architecture",
      "description": "Turns a workflow idea plus customer stack summary into a repeatable implementation blueprint that chooses the best validated starting point, identifies substitutions, and recommends a productized rollout path.",
      "status": ""
    },
    {
      "id": "22-crm-mapping-agent",
      "name": "CRM Mapping Agent",
      "category": "platform-architecture",
      "description": "Maps Salesforce, Dynamics 365, HubSpot, or custom CRM objects into canonical workflow fields so the same workflow pattern can run across different customer environments.",
      "status": ""
    },
    {
      "id": "23-delivery-adapter-agent",
      "name": "Delivery Adapter Agent",
      "category": "platform-architecture",
      "description": "Adapts one workflow output across Slack, Teams, email, and webhook surfaces while preserving meaning, urgency, and routing policy across different customer delivery stacks.",
      "status": ""
    },
    {
      "id": "24-meeting-source-adapter-agent",
      "name": "Meeting Source Adapter Agent",
      "category": "platform-architecture",
      "description": "Normalizes meeting, calendar, transcript, and note-taker signals across Gong, Zoom, Fireflies, Otter, Fathom, Teams, and similar systems so workflow logic stays reusable across customer stacks.",
      "status": ""
    },
    {
      "id": "25-identity-resolution-agent",
      "name": "Identity Resolution Agent",
      "category": "platform-architecture",
      "description": "Designs canonical person, account, owner, and channel identity rules across CRM, messaging, calendar, and meeting systems so reusable workflows stop breaking on alias drift and duplicate humans.",
      "status": ""
    },
    {
      "id": "26-payload-contract-designer",
      "name": "Payload Contract Designer",
      "category": "platform-architecture",
      "description": "Defines and hardens canonical payload contracts between workflow steps so different orchestrators and connector variants can swap in without breaking downstream logic.",
      "status": ""
    },
    {
      "id": "27-implementation-gap-analyst",
      "name": "Implementation Gap Analyst",
      "category": "platform-architecture",
      "description": "Evaluates a requested workflow or customer stack against validated assets, recipe coverage, and generic adapters so the team can prioritize what to productize next instead of reinventing the same build repeatedly.",
      "status": ""
    },
    {
      "id": "28-orchestrator-migration-advisor",
      "name": "Orchestrator Migration Advisor",
      "category": "platform-architecture",
      "description": "Designs migration plans between n8n, Make, Power Automate, Zapier, Workato, and custom code while preserving workflow order, state handling, payload contracts, and delivery behavior.",
      "status": ""
    },
    {
      "id": "29-adapter-qa-strategist",
      "name": "Adapter QA Strategist",
      "category": "platform-architecture",
      "description": "Designs golden-case coverage, release-gate checks, and regression strategy for reusable CRM, meeting, identity, and delivery adapters.",
      "status": ""
    },
    {
      "id": "30-rollout-readiness-architect",
      "name": "Rollout Readiness Architect",
      "category": "platform-architecture",
      "description": "Scores deployment readiness across connectors, mapping, identity, QA, ownership, and security so workflow launches happen with fewer preventable failures.",
      "status": ""
    }
  ],
  "mcp": [
    {
      "name": "find_account",
      "description": "Search for accounts by name or domain.",
      "usedBy": [
        "Account Plan Agent",
        "External Company News Agent",
        "Relationship Map Agent",
        "Customer Sentiment Agent",
        "Opportunity Agent",
        "MEDDPICC Agent",
        "Win Probability Agent",
        "Meeting Prep Agent",
        "QBR Generator Agent",
        "Multi-Threading Coach Agent",
        "Next Best Action Agent",
        "Whitespace Mapper Agent",
        "Pipeline Review Agent",
        "Competitive Battle Card Agent",
        "Executive Briefing Agent",
        "Renewal Risk Agent",
        "Handoff Agent",
        "Deal Debrief Agent",
        "Engagement Scorecard Agent",
        "Opportunity Insights Agent",
        "Workflow Template Architect",
        "CRM Mapping Agent",
        "Identity Resolution Agent"
      ]
    },
    {
      "name": "get_account_status",
      "description": "Account health, engagement score, and risk signals.",
      "usedBy": [
        "Account Plan Agent",
        "External Company News Agent",
        "Relationship Map Agent",
        "Customer Sentiment Agent",
        "Opportunity Agent",
        "MEDDPICC Agent",
        "Meeting Prep Agent",
        "QBR Generator Agent",
        "Multi-Threading Coach Agent",
        "Next Best Action Agent",
        "Whitespace Mapper Agent",
        "Pipeline Review Agent",
        "Competitive Battle Card Agent",
        "Executive Briefing Agent",
        "Renewal Risk Agent",
        "Handoff Agent",
        "Deal Debrief Agent",
        "Engagement Scorecard Agent",
        "Opportunity Insights Agent",
        "Workflow Template Architect"
      ]
    },
    {
      "name": "get_recent_account_activity",
      "description": "Meetings, emails, and calls in a time window.",
      "usedBy": [
        "Account Plan Agent",
        "External Company News Agent",
        "Relationship Map Agent",
        "Customer Sentiment Agent",
        "Meeting Prep Agent",
        "QBR Generator Agent",
        "Multi-Threading Coach Agent",
        "Next Best Action Agent",
        "Whitespace Mapper Agent",
        "Executive Briefing Agent",
        "Renewal Risk Agent",
        "Handoff Agent",
        "Engagement Scorecard Agent",
        "Workflow Template Architect",
        "Meeting Source Adapter Agent"
      ]
    },
    {
      "name": "get_opportunity_status",
      "description": "Deal stage, amount, close date, and activity.",
      "usedBy": [
        "Relationship Map Agent",
        "Opportunity Agent",
        "MEDDPICC Agent",
        "Win Probability Agent",
        "QBR Generator Agent",
        "Multi-Threading Coach Agent",
        "Next Best Action Agent",
        "Pipeline Review Agent",
        "Competitive Battle Card Agent",
        "Executive Briefing Agent",
        "Renewal Risk Agent",
        "Handoff Agent",
        "Deal Debrief Agent",
        "Opportunity Insights Agent",
        "CRM Mapping Agent"
      ]
    },
    {
      "name": "get_recent_opportunity_activity",
      "description": "Recent deal-level interactions and changes.",
      "usedBy": [
        "Opportunity Agent",
        "MEDDPICC Agent",
        "Win Probability Agent",
        "Competitive Battle Card Agent",
        "Deal Debrief Agent",
        "Opportunity Insights Agent",
        "Meeting Source Adapter Agent"
      ]
    },
    {
      "name": "get_engaged_people",
      "description": "Contacts with recent engagement on an account.",
      "usedBy": [
        "Account Plan Agent",
        "Relationship Map Agent",
        "Meeting Prep Agent",
        "QBR Generator Agent",
        "Multi-Threading Coach Agent",
        "Whitespace Mapper Agent",
        "Executive Briefing Agent",
        "Renewal Risk Agent",
        "Handoff Agent",
        "Deal Debrief Agent",
        "Engagement Scorecard Agent",
        "Opportunity Insights Agent",
        "Identity Resolution Agent"
      ]
    },
    {
      "name": "get_scorecard",
      "description": "Rep and team performance metrics.",
      "usedBy": [
        "Account Plan Agent"
      ]
    },
    {
      "name": "ask_sales_ai_about_account",
      "description": "Natural-language queries about any account (10–30s response).",
      "usedBy": [
        "External Company News Agent",
        "Relationship Map Agent",
        "Customer Sentiment Agent",
        "Meeting Prep Agent",
        "QBR Generator Agent",
        "Multi-Threading Coach Agent",
        "Next Best Action Agent",
        "Whitespace Mapper Agent",
        "Pipeline Review Agent",
        "Competitive Battle Card Agent",
        "Executive Briefing Agent",
        "Renewal Risk Agent",
        "Handoff Agent",
        "Engagement Scorecard Agent"
      ]
    },
    {
      "name": "ask_sales_ai_about_opportunity",
      "description": "Natural-language queries about any deal (10–30s response).",
      "usedBy": [
        "Relationship Map Agent",
        "Opportunity Agent",
        "MEDDPICC Agent",
        "Win Probability Agent",
        "Multi-Threading Coach Agent",
        "Pipeline Review Agent",
        "Competitive Battle Card Agent",
        "Handoff Agent",
        "Deal Debrief Agent",
        "Opportunity Insights Agent"
      ]
    },
    {
      "name": "top_records",
      "description": "Top accounts and opps by activity, risk, or value.",
      "usedBy": [
        "Opportunity Insights Agent"
      ]
    },
    {
      "name": "account_company_news",
      "description": "Recent news about an account's company.",
      "usedBy": [
        "External Company News Agent",
        "Customer Sentiment Agent",
        "QBR Generator Agent",
        "Renewal Risk Agent"
      ]
    }
  ]
};
